main.go
oauthproxy.go
options.go

```
-upstream-flush duration
force flush upstream responses after this duration(useful for streaming responses). 0(default) to never force flush
```

Add option to force flush upstream response

---

main.go

Skip logging handler entirely if requested.
The logging handler with its current implementation prevents the server for handling streaming requests.

Skip logging handler if requested

---

.travis.yml

Tests take less than a minute to run, let's not wait needlessly when they hang.

Timeout tests after 60 seconds

---

http.go
main.go
oauthproxy.go
oauthproxy_test.go
options.go
providers/openshift/provider.go
util/util.go

Add only the CA being handled to us in the configuration, and allow
loading a custom CA for contaicting Upstream (target) servers when
proxying.
Fixes #13 
Fixes #14

Better handling of CA trust roots loading

---

oauthproxy.go

Cherry-pick https://github.com/bitly/oauth2_proxy/pull/395
Fixes #18

Fix handling of redirect URI with --skip-provider-button 

---

http.go
oauthproxy.go
providers/openshift/provider.go
util/util.go

This is to allow the openshift provider to be backwards compatible
when it sets the default, which happens every time it does not
have an explicit configuration. Otherwise system roots can never
be automatically queried.
Users are advise to explicitly set the openshift-ca parameter if
they do not want to allow system roots to be trusted.
Addresses the comments on #15 after merge.

Allow adding the system roots in addition to a specified ca file

---

providers/openshift/provider.go
providers/openshift/provider_test.go

The array case in parseSubjectAccessReviews() did not use the index when encoding, so specifying an array of SARs for review was broken. Also refactor to reduce duplicate code.
@enj @simo5

Fix JSON array handling for --openshift-sar

---

README.md
main.go
oauthproxy.go
options.go
options_test.go

This option takes priority over --skip-auth-regex if set. When unset, all paths
are protected by default.
Fixes #42 
@smarterclayton @simo5 @enj please review :)

Add -bypass-auth-except-for to protect only paths matched by a regex

---

README.md
main.go
oauthproxy.go
options.go
providers/openshift/provider.go
providers/provider_default.go
providers/providers.go

This builds on --openshift-sar by having rules that apply to a specific hostname. In this way oauth-proxy can be used for multiple upstream hosts with different authorization rules. 
In doing this work I realized that the cookie once issued would work for any URL so I append the hostname to the cookie secret so that the cookie only validates for the hostname that it was issued with.

Add --openshift-sar-by-host option to specify SAR rules per hostname

---

README.md
main.go
oauthproxy.go
options.go
providers/openshift/provider.go
providers/openshift/provider_test.go

The OAuth token present in the `Authorization` header is not passed to
upstream if delegating authentication/authorization to OpenShift using
`--openshift-delegate-urls`.
This extracts the token from the `Authorization` header and passes it
to upstream via the usual `X-Forwarded-Access-Token` header.

Pass OAuth token if delegating to OpenShift

---

.travis.yml
test/e2e.sh
test/e2e/proxy_test.go
test/e2e/util.go

This PR makes a few changes to the e2e testing framework allowing it to run in travis-ci for all PRs. 
The changes include:
* Fetching, building, and starting an OpenShift 3.9 cluster
* Wait on a healthz check of oauth-proxy for each test
* Explicitly use the test namespace for oc commands

Run end-to-end tests in travis-ci

---

oauthproxy.go
oauthproxy_test.go

This shows up twice on initial auth and has caused some concern. I don't think it's that useful to log it.

Stop logging a missing cookie warning

---

http.go
main.go
options.go
providers/openshift/authentication.go
providers/openshift/provider.go

Let --tls-client-ca both enable client cert authentication in the OpenShift
provider and allow oauth-proxy to request a client cert. As a result this
removes the --client-ca-file option and changes --tls-client-ca to only allow
being specified once.
/cc @enj @ericavonb

Fix cert auth options

---

providers/openshift/provider.go

fixing http/s proxy handling for openshift provider

---

providers/openshift/provider.go

These URLs were previously built from login URL if they were not
specifically set by the user. In 4.0, the OAuth server gets separated
from the API server and therefore these endpoints would be by default
set improperly.
If an OAuth server different from the integrated one was set for
the OAuth flows, this could be broken even in earlier versions of
OpenShift.

fix review/user validation URLs

---

oauthproxy.go
options.go
providers/openshift/provider.go
providers/provider_data.go
providers/provider_default.go
providers/providers.go

Adds refetching of oauth endpoints and endpoints based on them
when a user tries to do a login. This happens unless these are
hardcoded by user config when the binary is started.
The provider will try to refetch the information also in the cases
where the fetching during login originally failed, but the endpoint
information is required for whatever different purpose.
-----
The number of refetched endpoints URLs will reduced when https://github.com/openshift/oauth-proxy/pull/100 is merged.
cc @openshift/sig-auth

openshift provider: refetch oauth endpoints on login

---

oauthproxy.go
oauthproxy_test.go
options.go
providers/openshift/provider.go
providers/provider_data.go
providers/provider_default.go
providers/providers.go

The code which was caching login and redeem URLs is actually
working in parallel which may cause nil dereferences as the cache
is being wiped out. Don't cache these urls at all.

providers: don't cache login and redeem URLs

---

main.go
options.go
providers/openshift/provider.go

@openshift/sig-auth 
Re: https://jira.coreos.com/browse/AUTH-245 and https://bugzilla.redhat.com/show_bug.cgi?id=1684169

Reload the OpenShift CAs during Redeem() and ReviewUser()

---

.travis.yml
oauthproxy.go

Basic auth looks at the Authorization header and checks that its
purpose is to serve for basic auth (starts with "Basic"). It would
log it if this check fails which might print the bearer token in
cases where e.g. service account already has its token and just wants
to access the armored endpoints.
cc @enj @mrogers950

Bug 1734390: don't log Authorization header when Basic Auth fails

---

providers/openshift/provider.go
providers/openshift/provider_test.go
util/util.go
util/util_test.go

Creating a new http.client object with every request, re-reading the
CA files, can cause the oauth-proxy container to eventually get
killed with OOM errors as the clients are not actually getting
released anywhere.
Re-use the clients based on checking whether their CA files actually
changed or not - the check for change is based on last-modified
timestamp and size metadata of each CA cert file.
-----
cc @deads2k @sttts

Bug 1759169: Fix high memory usage

---

http.go

Uses kube serving-cert reloader
/cc @marun

Bug 1801573: Reload serving certs

---

providers/openshift/provider.go

The HTTP requests made by the OpenShift provider do not currently apply a HTTP request timeout.  If the  OpenShift Oauth2 Server is in difficulties and fails to respond, the go routines of the HTTP client are leaked.  This problem is also invisible in the oauth-proxy logs.
~~This PR exposes the Provider's HTTP request timeout for configuration by the OAuth Proxy's standard mechanisms (command line, config file, environment).  I have left the default value for the HTTP request timeout to 0, so existing behaviour is unchanged.~~
This PR gives the Provider's HTTP request timeout a reasonable value (1min).

Bug 1826175: Make OpenShift provider's http requests timeout after 1min 

---

main.go
oauthproxy.go
options.go

Adds `-logout-url=url-to-log-out-of-sso` to be peer to https://github.com/openshift/api/blob/master/config/v1/types_console.go#L50-L63
I think this is logically comparable to https://github.com/openshift/console/blob/4efd97f82f824f56da6a1a627dbbd9d677ba9b63/frontend/public/module/auth.js#L72-L80
/assign @stlaz 
/cc @jcantrill 
The options for exposure are...
1. this PR which makes the redirect based on an oauth-proxy arg. Doing it like this prevents the web app from choosing a redirect URL that varies by user or by where a user is in the app itself. This is limiting, but easy.
1. create a different approach that allows a web app to go to the https://oauth-proxy/sign_out?redirect=foo. This allows webapps to choose any redirect based on any criteria. Based on a conversation with @spadgett, …

add logoutredirect URL to oauth-proxy

---

README.md
main.go
oauthproxy.go
options.go
options_test.go

Expose the [samesite](https://www.owasp.org/index.php/SameSite) cookie option for configuration.
Values of `lax` and `strict` can improve and mitigate some categories of cross-site traffic tampering.
As oauth-proxy is used to front other components, having this configuration option available makes a useful defence.
Based on Paul Groudas' <paul@clubhouse.io> work (https://github.com/oauth2-proxy/oauth2-proxy/commit/5d0827a)

Add configuration for cookie 'SameSite' value.

---

string_array.go
string_array_test.go

Golang flags attempt to use an empty struct when they print
defaults for usage information.

Bug 1884565: don't segfault on wrong option combination

---

oauthproxy.go

Bug 1879878: remove logging when authz header is present but basic auth is not attempted

---

providers/openshift/provider.go

This prevents log flooding of anomoys requests with no bearer token. This also prevents logging of empty authorizer denial reasons with an initial request against oauth-proxy before it redirects to the login page.
/cc @standa @sttts

Bug 1958158: providers/openshift: remove logging of authorizer decisions

---

main.go
oauthproxy.go
templates.go
version.go

We stopped versioning the binary in OpenShift 4.x

Bug 1980235: deprecate version

---

providers/openshift/provider.go
providers/openshift/provider_test.go

Newer oauth-proxy versions can be used in older clusters where
the oauth-server certificate is not present. We should not fail
client creation in those cases.
/assign @s-urbaniak 
/cc @openshift/openshift-team-multi-cluster-maintainers

Bug 2026860: ocp provider: don't fail client creation if oauth-server cert is not present

---

http.go
main.go

When a pod is evicted, the container runtime will send a TERM signal to the PID 1 of all containers. If a container doesn't catch the signal, the process will exit with a non-zero code and Kubernetes might consider the pod status to be Failed.
See
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

OCPBUGS-14033: Handle TERM signal gracefully

---

README.md
main.go
oauthproxy.go
oauthproxy_test.go
options.go

Currently, there is no support for configuring the timeout between the proxy and the backends, and as such, the default timeout of **30 seconds** is applied (as per Go's standard library defaults). When the timeout occurs, the user will see an "http: proxy error: context canceled" in the logs, and the remote client will receive a **502** error.
The default timeout might not be sufficient for some services, especially as every upstream service differs, and the abrupt connection termination might not be desirable. Typically, most upstream services only send response headers after they have gathered/processed all necessary data.
Thus, add a new command-line switch called `--upstream-timeout`, allowing users to configure the timeout setting.
Note: this change is, almost entirely, a backport …

APPSRE-7970: Add support for configuring upstream timeout

---

contrib/sidecar.yaml

Replaced:
`apiVersion: v1`
with:
`apiVersion: route.openshift.io/v1`
`apiVersion: v1` doesn't work

fix route apiVersion

---

.ci-operator.yaml
Dockerfile
oauthproxy_test.go

[4.13] OCPBUGS-16805: Updating golang-github-openshift-oauth-proxy images to be consistent with ART

---

test/e2e/proxy_test.go

- We’re unable to find a stable and accessible OAuth-proxy image, which is causing a bug that we haven’t fully resolved yet. @ibihim  made a PR to address this , but it’s not a complete solution since the image path doesn’t seem consistently available.
- @ibihim  tried referencing the OAuth-proxy image from the OpenShift openshift namespace, but it didn’t work reliably.
- There’s an imagestream for OAuth-proxy in the openshift namespace, which we might be able to reference in tests, but you're not certain of the correct Docker URL format for it. Also, it’s possible that there are permission issues, which could be why the image isn’t accessible when referenced this way.

OCPBUGS-44319: Fix oauth-proxy e2e-component tests

---

OWNERS

Add to owners:
- ibihim
- liouk
Remove from owners:
- sttts
- stlaz
sttts and stlaz left the org. ibihim and liouk are the current maintainers.

no-jira: OWNERS: add Krzys (ibihim) and Ilias (liouk) as reviewers
